"use client";
import {useEffect,useState} from "react";
const initial={goal:17,xp:1240,streak:12,scores:{Probabilidades:[58,43],Funções:[71,61],Contagem:[68,52],"Números complexos":[79,54],Álgebra:[76,70]}};
const Q=[
["P(A∩B)=0,18 e P(B)=0,60. Quanto vale P(A|B)?",["0,30","0,108","0,42","0,78"],0,"P(A|B)=0,18/0,60=0,30."],
["Em P(A|B), qual é o universo relevante?",["O universo original","Apenas B","Apenas A","A∪B"],1,"A condição B restringe o universo relevante."],
["P(A|B)=0,25 e P(B)=0,60. Quanto vale P(A∩B)?",["0,15","0,35","0,40","0,85"],0,"0,25×0,60=0,15."]
];
export default function App(){
 const [s,setS]=useState(initial),[screen,setScreen]=useState("welcome");
 useEffect(()=>{try{let x=JSON.parse(localStorage.getItem("a11"));if(x){setS(x);setScreen("home")}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("a11",JSON.stringify(s))}catch{}},[s]);
 const go=x=>setScreen(x);
 if(screen==="welcome")return <Welcome go={go}/>;
 if(screen==="onboard")return <Onboard s={s} setS={setS} go={go}/>;
 if(screen==="diag")return <Diag go={go}/>;
 if(screen==="mission")return <Mission s={s} setS={setS} go={go}/>;
 if(screen==="train")return <Train go={go}/>;
 if(screen==="progress")return <Progress s={s} go={go}/>;
 if(screen==="exams")return <Exams go={go}/>;
 if(screen==="parent")return <Parent go={go}/>;
 return <Home s={s} go={go} reset={()=>{localStorage.removeItem("a11");setS(initial);go("welcome")}}/>
}
const Logo=()=> <div className="logo">A<span>+</span> EXAMES</div>;
function Welcome({go}){return <main className="dark center"><section className="hero"><Logo/><p className="eyebrow">PREPARAÇÃO INTELIGENTE PARA EXAMES NACIONAIS</p><h1>A tua melhor nota<br/><em>começa aqui.</em></h1><p>A A+ descobre onde estás a perder pontos e decide o que vale mais a pena estudar hoje.</p><button onClick={()=>go("onboard")}>Descobrir o meu nível →</button><div className="features"><span>⚡ 10–20 min/dia</span><span>🎯 Adaptativo</span><span>📈 Progresso real</span></div></section></main>}
function Onboard({s,setS,go}){return <Shell><Logo/><p className="eyebrow">O TEU OBJETIVO</p><h1>Que nota queres alcançar?</h1><p className="muted">Isto ajusta a exigência das Missões. Não é uma previsão da tua nota.</p><div className="goals">{[12,14,16,17,18,19,20].map(x=><button className={s.goal===x?"sel":""} onClick={()=>setS({...s,goal:x})}>{x}<small> valores</small></button>)}</div><button className="primary" onClick={()=>go("diag")}>Começar diagnóstico</button></Shell>}
function Diag({go}){return <Shell><Logo/><p className="eyebrow">DIAGNÓSTICO ADAPTATIVO</p><h1>Vamos descobrir onde podes ganhar mais pontos.</h1><div className="notice"><b>Protótipo integrado</b><span>Na versão real, o diagnóstico selecionará questões dinamicamente até existir evidência suficiente por competência.</span></div><div className="fake"><span>✓ Álgebra base</span><span>✓ Funções</span><span>◌ Probabilidades</span><span>◌ Contagem</span></div><button className="primary" onClick={()=>go("home")}>Simular diagnóstico concluído →</button></Shell>}
function Home({s,go,reset}){let avg=Math.round(Object.values(s.scores).reduce((a,x)=>a+x[0],0)/5);return <main className="dark"><section className="wrap"><header><div><Logo/><small>MATEMÁTICA A · PROTÓTIPO</small></div><div>🔥 {s.streak} dias · <b>{s.xp} XP</b></div></header><div className="hello"><div><p>Boa noite 👋</p><h1>O que vamos conquistar hoje?</h1></div><strong>{avg}<small>/100<br/>preparação</small></strong></div><div className="mission"><div><small>🎯 MISSÃO DE HOJE · ~12 MIN</small><h2>Probabilidade condicionada</h2><p>É uma das tuas maiores oportunidades de evolução. A A+ considerou domínio, confiança, pré-requisitos e o teu objetivo de {s.goal} valores.</p></div><button onClick={()=>go("mission")}>Começar →</button></div><div className="navgrid">{[["🧠","Treinar","Escolhe matéria e nível.","train"],["📝","Exames","Avaliação em contexto de prova.","exams"],["📈","Progresso","Domínio + confiança.","progress"],["👨‍👩‍👧","Área dos pais","Acompanhamento parental.","parent"]].map(x=><button onClick={()=>go(x[3])}><b>{x[0]} {x[1]}</b><span>{x[2]}</span></button>)}</div><div className="card"><h3>Estado atual</h3>{Object.entries(s.scores).map(([k,v])=><div className="skill"><span>{k}</span><div className="bar"><i style={{width:v[0]+"%"}}/></div><b>{v[0]}</b><small>conf. {v[1]}%</small></div>)}</div><button className="reset" onClick={reset}>Recomeçar protótipo</button></section></main>}
function Mission({s,setS,go}){const [i,setI]=useState(0),[sel,setSel]=useState(null),[fb,setFb]=useState(null),[ok,setOk]=useState(0);let q=Q[i];function answer(n){if(fb)return;setSel(n);let c=n===q[2];if(c)setOk(ok+1);setFb(c?["good","✓ Correto",q[3]]:["bad","A A+ detetou uma hipótese.","A próxima evidência ajuda a distinguir uma falha de conceito de uma falha de cálculo."])}function next(){if(i<2){setI(i+1);setSel(null);setFb(null)}else{let ns=JSON.parse(JSON.stringify(s));let d=ok>=1?5:-4;ns.scores.Probabilidades[0]+=d;ns.scores.Probabilidades[1]=Math.min(96,ns.scores.Probabilidades[1]+14);ns.xp+=110;setS(ns);go("progress")}}return <Shell><Logo/><div className="notice"><b>Porque esta pergunta?</b><span>A A+ está a recolher evidência sobre probabilidade condicionada. Uma resposta isolada nunca decide o teu nível.</span></div><p className="eyebrow">EVIDÊNCIA {i+1}</p><h2>{q[0]}</h2><div className="opts">{q[1].map((x,n)=><button className={(sel===n?"sel ":"")+(fb&&n===q[2]?"correct ":"")+(fb&&sel===n&&n!==q[2]?"wrong":"")} onClick={()=>answer(n)}><b>{String.fromCharCode(65+n)}</b>{x}</button>)}</div>{fb&&<div className={"feedback "+fb[0]}><b>{fb[1]}</b><span>{fb[2]}</span><small>Ver resolução passo a passo</small></div>}<button disabled={!fb} className="primary" onClick={next}>Continuar</button></Shell>}
function Train({go}){return <Shell><Back go={go}/><p className="eyebrow">TREINO LIVRE</p><h1>O que queres praticar?</h1><p className="muted">Podes escolher livremente. <b>O treino não altera diretamente a avaliação A+.</b> Pode apenas criar uma hipótese a confirmar numa Missão ou Exame.</p><div className="chips">{["Probabilidades","Funções","Contagem","Complexos","Álgebra"].map(x=><button>{x}</button>)}</div><h3>Nível</h3><div className="chips">{["✨ Adaptado","🟢 Básico","🔵 Intermédio","🟣 Avançado","🔥 Desafio"].map(x=><button>{x}</button>)}</div><button className="primary" onClick={()=>go("home")}>Simular treino concluído</button></Shell>}
function Progress({s,go}){return <Shell><Back go={go}/><p className="eyebrow">PROGRESSO</p><h1>Domínio não é o mesmo que certeza.</h1>{Object.entries(s.scores).map(([k,v])=><div className="prog"><b>{k}</b><span>Domínio {v[0]}</span><div className="bar"><i style={{width:v[0]+"%"}}/></div><span>Confiança {v[1]}%</span><div className="bar green"><i style={{width:v[1]+"%"}}/></div></div>)}<div className="notice"><b>Porque mostramos os dois?</b><span>Um domínio alto baseado em pouca evidência deve ser tratado de forma diferente de um domínio confirmado em vários formatos e momentos.</span></div></Shell>}
function Exams({go}){return <Shell><Back go={go}/><p className="eyebrow">EXAMES</p><h1>Avaliação em contexto de prova.</h1><div className="exam"><b>⚡ Mini-exame</b><span>15–25 min · várias competências</span></div><div className="exam"><b>📝 Exame de treino A+</b><span>Prova completa criada para o teu nível</span></div><div className="exam locked"><b>🏛️ Exames oficiais</b><span>🔒 A aguardar esclarecimento sobre utilização dos conteúdos oficiais</span></div><div className="notice"><b>Mais tarde</b><span>Respostas desenvolvidas em papel, fotografia e correção assistida por IA exigem uma camada própria de controlo de qualidade. Não vou fingir que isto está resolvido na primeira beta.</span></div></Shell>}
function Parent({go}){return <Shell><Back go={go}/><p className="eyebrow">ÁREA DOS PAIS · PRÉ-VISUALIZAÇÃO</p><h1>Acompanhar progresso, não vigiar respostas.</h1><div className="parent"><div><b>Aluno ligado</b><span>Matemática A</span></div><strong>68<small>/100</small></strong></div><div className="metrics"><div><b>🔥 12</b><span>dias</span></div><div><b>4/5</b><span>missões</span></div><div><b>+6</b><span>evolução</span></div></div><div className="notice"><b>Ligação segura</b><span>O aluno envia um convite. Não haverá pesquisa pública de utilizadores. Os pais recebem progresso, simulados, tempo de estudo e evolução.</span></div></Shell>}
function Back({go}){return <button className="back" onClick={()=>go("home")}>← Voltar</button>}
function Shell({children}){return <main className="light"><section className="panel">{children}</section></main>}
